- name: Deploy Virtual Machine
  hosts: localhost
  connection: local

  tasks:
    - name: Create VM NIC
      azure_rm_networkinterface:
        name: '{{ vm_name }}-nic'
        os_type: Linux
        resource_group: "{{ resource_group }}"
        security_group_name: '{{ vm_name }}-nsg'
        subnet_name: "{{ subnet_name }}"
        virtual_network_name: "{{ vnet_name }}"
        ip_configurations:
          - name: "{{ vm_name }}"
            public_ip_address_name: "{{ vm_public_ip_name }}"
    
    - name: Create VM
      azure_rm_virtualmachine:
        admin_username: "{{ admin_username }}"
        location: "{{ location }}"
        managed_disk_type: Standard_LRS
        name: "{{ vm_name }}"
        network_interface_names: '{{ vm_name }}-nic'
        os_type: Linux
        resource_group: "{{ resource_group }}"
        short_hostname: "{{ vm_name }}"
        vm_size: Standard_DS3_v2
        ssh_password_enabled: false
        ssh_public_keys:
          - path: /home/{{ admin_username }}/.ssh/authorized_keys
            key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        image:
          offer: UbuntuServer
          publisher: canonical
          sku: '18.04-LTS'
          version: 18.04.201811010
        tags: 
          Role: DNS
          Application: PiHole

    - name: Allow web traffic
      azure_rm_securitygroup:
        resource_group: "{{ resource_group }}"
        name: '{{ vm_name }}-nsg'
        rules:
          - name: AllowHttp
            protocol: Tcp
            source_address_prefix: '*'
            destination_port_range: 80
            access: Allow
            priority: 110
            direction: Inbound